name: Continuous Deployment

on:
  # Run the workflow on push or pull request events to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows manual triggering of the workflow from the Actions tab
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository to access the code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies listed in requirements.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Run the Python script
      - name: Run Python Script
        run: |
          python main.py
